#include "evtolpwrsim.h"
#include "ui_evtolpwrsim.h"
#include <QStandardItemModel>
#include <QStringList>
#include <vector>
#include <random>
#include <queue>
#include <algorithm>
#include <iostream>
#include <iomanip>
#include <thread> // Added for threading
#include <mutex>  // Added for synchronization

#include "evtolpwrsim.h"
#include "ui_evtolpwrsim.h" // Includes the generated UI header that defines the 'ui' object

/*
 * THE CONSTRUCTOR
 * This is called when the main window object 'w' is created in main.cpp.
 *
 * @param parent: Usually NULL in main(), but allows for memory management
 *                within the Qt Object Tree.
 */
eVtolPwrSim::eVtolPwrSim(QWidget *parent)
    : QMainWindow(parent)       // Initialize the base class (QMainWindow)
    , ui(new Ui::eVtolPwrSim)   // Allocate memory for the UI pointer (the "View" components)
{
    /*
     * 1. INITIALIZE THE UI
     * This function is generated by Qt Creator's 'uic' tool. It takes the XML
     * from the .ui file and creates the actual C++ widget objects (such as
     * QTableView, buttons, and labels) and places them inside the window.
     */
    ui->setupUi(this);

    /*
     * 2. AUTOMATIC EXECUTION / INITIAL SIMULATION
     * This line manually triggers the 'slot' (function) associated with the
     * 'Run Simulation' button as soon as the program starts.
     *
     * In the Model-View context: This is where the Model is set with
     * data and calls 'ui->tableView->setModel(myModel)' so the table is
     * populated immediately upon opening.
     */
    on_runPwrSimBtn_clicked();
}


/*
 * THE DESTRUCTOR
 * This is called automatically when the eVtolPwrSim object goes out of scope
 * or is explicitly deleted (e.g., when the application closes).
 */
eVtolPwrSim::~eVtolPwrSim()
{
    /*
     * CLEANING UP THE UI POINTER
     *
     * In the constructor, 'ui(new Ui::eVtolPwrSim)' was used to allocate memory
     * on the heap for all the interface elements (buttons, QTableView, etc.).
     *
     * Calling 'delete ui' ensures that all the memory used by the auto-generated
     * UI class is freed back to the system.
     *
     * NOTE: You do not usually need to manually delete individual widgets
     * (e.g. table view) if they were created with 'this' as a parent,
     * because Qt's "Parent-Child" system handles that automatically.
     * However, the 'ui' object itself is not a widget; it's a container class,
     * so it must be deleted here.
     */
    delete ui;
}

/*
 * THE EXTRACTED HELPER FUNCTION
 * This function converts a list of strings into a list of QStandardItems.
 *
 * @param rowData: A reference to a list of strings (raw data for one row).
 * @param items:   A reference to a list of pointers where the new model
 *                 items will be stored.
 */
void eVtolPwrSim::extracted(QStringList &rowData,
                            QList<QStandardItem *> &items) {

    /*
     * THE LOOP
     * Iterates through every string in the rowData list.
     * 'const QString &' is used for efficiency to avoid copying the string.
     */
    for (const QString &text : rowData) {

        /*
         * CREATING THE MODEL ITEM
         * 'new QStandardItem(text)' creates a new data container for the Model.
         * This object stores the text, but can also store fonts, colors,
         * and checkstate data for a single cell in the QTableView.
         */

        /*
         * THE STREAM OPERATOR (<<)
         * In Qt, the '<<' operator is used to append items to a QList.
         * This adds the newly created item pointer to the 'items' list.
         */
        items << new QStandardItem(text);
    }
}


// Runs the simulation
void eVtolPwrSim::on_runPwrSimBtn_clicked() {
    // Disable the button so the user doesn't spam-click it
    ui->runPwrSimBtn->setEnabled(false);
    ui->simReportHdr->setText("Simulation running in background...");

    // Setup the FutureWatcher to notify us when the work is done
    auto watcher = new QFutureWatcher<void>(this);

    // Connect the 'finished' signal to our results-handling function
    connect(watcher, &QFutureWatcher<void>::finished, this, &eVtolPwrSim::handleSimFinished);
    // Ensure the watcher is deleted automatically after it's done
    connect(watcher, &QFutureWatcher<void>::finished, watcher, &QFutureWatcher<void>::deleteLater);

    /* Wrap the simulation in QtConcurrent::run
     * This launches the entire multi-threaded block preventing
     * the UI from blocking while waiting for the join()/s.
     * QFUTURE: THE "RECEIPT"
     * QFuture is a template class that represents the result of an asynchronous
     * computation. Think of it as a 'receipt' for a task that is happening
     * in the background. You can use it to check if the simulation is still
     * running or wait for it to finish.
     * QTCONCURRENT::RUN: THE THREAD STARTER
     * This tells Qt to find an available thread in the global thread pool
     * and run the provided code there. This prevents the "Not Responding"
     * freeze in your UI while the power simulation calculates.
     * THE LAMBDA FUNCTION [this](no parameters) { simulation code }
     * This is an anonymous, "in-place" function.
     *     [this]: The "Capture" clause. It allows the background thread
     *     to access the variables and functions of this eVtolPwrSim class.
     *     (): The parameter list (empty here).
     * The 'run' function returns immediately, and the simulation code
     * starts executing in parallel. */
    QFuture<void> future = QtConcurrent::run([this]() {
        // Main thread Random Number Generator for initial setup
        /*
        * THE SEED (The "Source of Entropy")
        * std::random_device is a non-deterministic random number generator.
        *
        * Think of this as a hardware-based request for a truly random starting
        * point (often using system noise or hardware interrupts). It is used
        * to "seed" the math engine so that every time you run your eVTOL
        * simulation, you don't get the exact same "random" results.
        */
        std::random_device rd;

        /*
        * THE ENGINE (The "Math Brain")
        * std::mt19937 is the "Mersenne Twister" algorithm.
        *
        * This is a highly respected mathematical engine that produces a sequence
        * of pseudo-random numbers. It has a very long period (it won't repeat
        * the same sequence for a massive amount of time).
        *
        * gen(rd()): Initializes the engine by passing it a value from our
        * random_device. This ensures the engine starts at a unique
        * point in its sequence every time the program runs.
        */
        std::mt19937 gen(rd());

        /* Initialize the shared class members (fleetSpecs, counts and stats) and
         * instatiate the vehicles vector */
        fleetSpecs = {
                      {"Alpha", 120, 320, 0.6, 1.6, 4, 0.25},
                      {"Bravo", 100, 100, 0.2, 1.5, 5, 0.10},
                      {"Charlie", 160, 220, 0.8, 2.2, 3, 0.05},
                      {"Delta", 90, 120, 0.62, 0.8, 2, 0.22},
                      {"Echo", 150, 30, 0.3, 5.8, 2, 0.61}};

        // Random Distribution of 20 vehicles
        /*
         * RESETTING THE DATA
         * 'counts' ia std::vector<int> container.
         *
         * .assign(5, 0): This does two things:
         *    a) Ensures the container has exactly 5 elements.
         *     b) Sets the value of every single element to 0.
         *
         *  These five counts represent the number of air vehicles
         *  for each of the five companies.
        */
        counts.assign(5, 0);

        /*
         * GENERATE THE RANDOM AIR VEHICLE COUNTS
         * std::uniform_int_distribution<>(0, 4):
         * This creates a distribution that produces integers between 0 and 4
         * inclusive (0, 1, 2, 3, or 4). This matches our 5 'counts' slots.
         *
         * (gen): Pass the Mersenne Twister engine (created earlier) into
         * the distribution to get an actual random number.
         *
         * After this loop finishes, the sum of all values in 'counts' will
         * be 20, but they will be distributed randomly across the 5 slots.
         */
        for (int i = 0; i < 20; ++i) {

            int randomIndex = std::uniform_int_distribution<>(0, 4)(gen);

            /*
             * INCREMENT THE COUNTER
             * counts[randomIndex]++:
             * This takes the previously generated random index and increments the
             * value at that position in our list. */

            counts[randomIndex]++;
        }


        std::vector<EVTOLModel> vehicles;
        stats.assign(5, EVTOLVehicle::Stats()); // Reset stats for new run

        for (int i = 0; i < 5; ++i) {
            for (int j = 0; j < counts[i]; ++j) {
                vehicles.push_back(EVTOLModel(fleetSpecs[i]));
            }
        }

        // Simulation Parameters
        double simTimeLimit = 3.0; // 3 hours

        // Shared Resources
        std::priority_queue<double, std::vector<double>, std::greater<double>> chargers;
        for (int i = 0; i < 3; ++i)
            chargers.push(0.0);

        // Mutexes for synchronization
        std::mutex chargerMutex;
        std::mutex statsMutex;

        // Thread Container
        std::vector<std::thread> threads;

        /* --- RUN SIMULATION ---
         * Iterate through the 'vehicles' vector (20 vehicles).
         * Each iteration launches a separate thread to simulate that vehicle's 3-hour journey
         * in parallel cores. */
        for (unsigned long i = 0; i < vehicles.size(); ++i) {

           /* THREADING & LAMBDA EXPLAINED:
            * threads.emplace_back(...) constructs a std::thread object directly inside the
            * vector.
            * The `[&, i]` is a "Capture Clause":
            *   - `&`: Capture by reference. This gives the thread access to shared objects
            *          such as 'chargers', 'stats', and 'mutexes' defined in the main function's
            *          scope.
            *   - `i`: Capture by value. We pass the current loop index so each thread knows
            *          exactly which vehicle in the vector it is responsible for.
            * The `() { ... }` is the Lambda Body— where the simulation code thread is executed. */
            threads.emplace_back([&, i]() {

                /* THREAD-SAFE RANDOMNESS:
                * We initialize a local random num generator (RNG0 inside the thread.
                * If we used the global 'gen' from the main thread,
                * the program would likely crash because 'std::mt19937' is not thread-safe.
                * 'threadRd' gets a seed from the hardware, and 'threadGen' generates the sequence. */
                std::random_device threadRd;
                std::mt19937 threadGen(threadRd());

                double currentTime = 0; // The vehicle's personal "clock" (starts at hour 0.0)
                int typeIdx = -1;       // Used to map this vehicle back to its Company for final stats

                // Identify the company index by comparing the vehicle name to the fleet list
                for (int k = 0; k < 5; ++k)
                {
                    if (vehicles[i].specs.name == fleetSpecs[k].name)
                    {
                        typeIdx = k;
                    }
                }

                /* OPTIMIZATION - LOCAL ACCUMULATORS:
                 * We store stats in local variables first. Locking a mutex is "expensive" (slows down the CPU).
                 * By using local variables, the thread only locks the global 'statsMutex' ONCE at the
                 * very end, rather than every time the vehicle flies or charges. */
                double localFlightTime = 0;
                double localDistance = 0;
                double localPassMiles = 0;
                int    localFlights = 0;
                int    localFaults = 0;
                double localChargeTime = 0;
                int    localCharges = 0;

                // Discrete Event Loop: Continue until the vehicle's clock reaches the 3-hour limit
                while (currentTime < simTimeLimit) {

                    // --- FLIGHT PHASE ---
                    // getFlightDuration() returns how long the battery lasts (e.g., 0.5 hours).
                    double flightDuration = vehicles[i].getFlightDuration();

                    /* THE MIN FUNCTION (std::min):
                    * Logic: actualFlight = min(Battery Life, Remaining Sim Time).
                    * If a battery lasts 1 hour, but only 0.2 hours are left in the simulation,
                    * the vehicle only flies for 0.2 hours. This prevents the "over-flying" bug. */
                    double actualFlight = std::min(flightDuration, simTimeLimit - currentTime);

                    if (actualFlight <= 0) break; // Exit loop if no time remains

                    // Physics: Distance = Speed * Time
                    double distance = actualFlight * vehicles[i].specs.cruiseSpeed;

                    // Log the local statistics for this flight segment
                    localFlightTime += actualFlight;
                    localDistance += distance;
                    localPassMiles += (distance * vehicles[i].specs.passengers);
                    localFlights++;

                    /* BERNOULLI DISTRIBUTION:
                    * Think of this as a "weighted coin flip."
                    * vehicles[i].specs.faultProb is the chance of failure per hour.
                    * By multiplying it by 'actualFlight', we scale the risk to the length of the flight.
                    * faultDist(threadGen) returns 'true' if the "coin" lands on a fault. */
                    std::bernoulli_distribution faultDist(vehicles[i].specs.faultProb * actualFlight);
                    if (faultDist(threadGen))
                        localFaults++;

                    // Advance the vehicle's clock forward by the time spent in the air
                    currentTime += actualFlight;

                    // --- CHARGING PHASE ---
                    // This block executes only if there is still time left in the 3-hour simulation window.
                    if (currentTime < simTimeLimit) {
                        double startCharge = 0;
                        double endCharge = 0;

                        /* MUTEX & PRIORITY QUEUE LOGIC:
                        * A Mutex is a "talking stick." Only one thread can hold it at a time.
                        * The 'chargers' priority queue is a "Min-Heap."
                        * .top() always gives us the charger that is finishing its work the soonest. */
                        {
                            // lock_guard ensures that no other thread modifies 'chargers' while we are.
                            std::lock_guard<std::mutex> lock(chargerMutex);

                            // Get the earliest available time a charger is free
                            double chargerReadyTime = chargers.top();
                            chargers.pop(); // Remove it from the queue (we are now using it)

                            /* WAITING LOGIC (std::max):
                            * If the vehicle arrives at 1.0 but the charger isn't free until 1.2,
                            * the vehicle MUST wait until 1.2.
                            * If the vehicle arrives at 1.5 but the charger was free at 1.2,
                            *  the vehicle starts immediately at 1.5. */
                            startCharge = std::max(currentTime, chargerReadyTime);
                            endCharge = startCharge + vehicles[i].specs.chargeTime;

                            // Put the charger back in the queue with its NEW free-time (endCharge)
                            chargers.push(endCharge);

                        } // Mutex is released here. Other threads can now access the queue.

                        // Calculate the actual charge received before the 3-hour global cutoff
                        double actualChargeTime = std::min(endCharge, simTimeLimit) - startCharge;

                        if (actualChargeTime > 0) {
                            localChargeTime += actualChargeTime;
                            localCharges++;
                        }

                        /* Advance the vehicle's personal clock to the the point that it finishes
                        * charging, or would have finished charging. */
                        currentTime = endCharge;
                    }
                }

                /* FINAL STATS MERGE:
                * Now that the 3-hour simulation is over for this specific vehicle,
                * we lock the global stats once to add our local totals to the company-wide totals. */
                {
                    std::lock_guard<std::mutex> lock(statsMutex);
                    stats[typeIdx].totalFlightTime += localFlightTime;
                    stats[typeIdx].totalDistance += localDistance;
                    stats[typeIdx].totalPassengerMiles += localPassMiles;
                    stats[typeIdx].flightCount += localFlights;
                    stats[typeIdx].totalFaults += localFaults;
                    stats[typeIdx].totalChargeTime += localChargeTime;
                    stats[typeIdx].chargeCount += localCharges;
                }
            }); // End of Thread Lambda
        }

        /*  --- THREAD SYNCHRONIZATION (The "Wait" Phase) ---
        *  This loop causes program execution to wait for all threads to finish ensuring the main program
        *  doesn't try to show results before the vehicles are actually done flying and charging in their
        *  background threads.

        THE 'auto' KEYWORD:
        * 'auto' tells the compiler to automatically deduce the data type of the variable 't'.
        * Since 'threads' is a std::vector<std::thread>, the compiler knows 't' is a 'std::thread'.
        * The '&' (reference) is vital: it prevents the code from trying to "copy" the thread
        * object (which is illegal in C++). It points directly to the existing thread in the vector. */
        for (auto &t : threads) {

            /* t.joinable() is a safety check. A thread is "joinable" if it has been started and hasn't
            * been "joined" or "detached" yet. Attempting to join a thread that isn't joinable will cause
            * the program to crash with a 'std::system_error'. This check ensures the thread is valid to wait on. */
            if (t.joinable()) {

                /* t.join():
             * This is a "blocking" call. It tells the main thread (the UI thread):
             * "Stop right here and wait until this specific vehicle thread ('t') finishes
             * its 3-hour simulation loop."
             *
             * Without join(), the main thread would zoom past this loop, try to calculate
             * averages with zeros or incomplete data, and display an empty table while
             * the background threads were still crunching numbers.
             *
             * Once t.join() returns, we are 100% certain that the vehicle's data has
             * been safely moved into the global 'stats' vector via the mutex. */
                t.join();
            }
        }
    }); // end of QConcurrent runs in parallel of GUI Loop

    // 4. Give the future to the watcher to start monitoring
    watcher->setFuture(future);
}

void eVtolPwrSim::handleSimFinished() {
    // This code runs on the MAIN UI THREAD once all background threads are joined.
    ui->runPwrSimBtn->setEnabled(true);
    ui->simReportHdr->setText("Simulation Complete!");

    // Initialize the model (UI Logic - runs on main UI thread after the simulation)
    if (ui->simReportHdr)
        ui->simReportHdr->setText("eVTOL Simulation Results (3 Hours, 20 Vehicles)");

    QStandardItemModel *simResultsModel = new QStandardItemModel(this);
    QStringList colHdrLbls;
    colHdrLbls << "Company" << "Count" << "Avg Flight" << "Avg Dist"
               << "Avg Charge"
               << "Faults" << "PAX Miles";
    simResultsModel->setHorizontalHeaderLabels(colHdrLbls);

    for (int i = 0; i < 5; ++i) {
        double avgFlight = stats[i].flightCount > 0
                               ? stats[i].totalFlightTime / stats[i].flightCount
                               : 0;
        double avgDist = stats[i].flightCount > 0
                             ? stats[i].totalDistance / stats[i].flightCount
                             : 0;
        double avgCharge = stats[i].chargeCount > 0
                               ? stats[i].totalChargeTime / stats[i].chargeCount
                               : 0;
        QStringList rowData;
        rowData << fleetSpecs[i].name.c_str() << QString::number(counts[i])
                << QString::number(avgFlight) << QString::number(avgDist)
                << QString::number(avgCharge)
                << QString::number(stats[i].totalFaults)
                << QString::number(stats[i].totalPassengerMiles);

        std::cout << std::left << std::setw(10) << fleetSpecs[i].name
                  << std::setw(8) << counts[i]
                  << std::setw(15) << avgFlight
                  << std::setw(15) << avgDist
                  << std::setw(12) << avgCharge
                  << std::setw(10) << stats[i].totalFaults
                  << stats[i].totalPassengerMiles << std::endl << std::flush;

        QList<QStandardItem *> items;
        extracted(rowData, items);
        simResultsModel->appendRow(items);
    }

    if(ui->resultsTblView) {
        ui->resultsTblView->horizontalHeader()->setDefaultAlignment(Qt::AlignLeft | Qt::AlignVCenter);
        ui->resultsTblView->setModel(simResultsModel);
    }
}
